---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./base/apps
  prune: true
  validation: client
---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: infra
  namespace: flux-system
spec:
  interval: 1m
  approvePlan: "auto"
  path: ./base/terraform/infra
  backendConfig:
    disable: true
  cliConfigSecretRef:
    name: tfe-cli-config
  sourceRef:
    kind: GitRepository
    name: flux-system
---
